"""Initial migration.

Revision ID: c80aca7c276c
Revises: 4ea00378ff6c
Create Date: 2023-10-27 12:06:02.777929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c80aca7c276c'
down_revision = '4ea00378ff6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=True))

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.String(length=200), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('address')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('quantity')
        batch_op.drop_column('category')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('review')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('address')

    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_reviews_product_id_products'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_reviews_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
